CREATE TABLE PERSON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	pass varchar(20) not null
);

insert into PERSON (name, pass) values ('dmitry', '123456');
insert into PERSON (name, pass) values ('alex', '123456');